# Generated by Django 3.0 on 2019-12-17 18:10

from django.db import migrations, models
import django.utils.timezone
import ghost_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=280)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_votes', models.IntegerField(default=0)),
                ('secret_code', models.CharField(default=ghost_backend.models.random_string, max_length=6)),
            ],
        ),
    ]
